{"name": "test_login02[data1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '' == '账号或密码错误!'\n  + 账号或密码错误!", "trace": "self = <test_login.TestLogin object at 0x0443E350>\ndata = {'dataName': '密码超过6位登录失败', 'errorMsg': '', 'membMobile': '15691750516', 'membPassword': '1234567890'}\nlogin_driver = (<PageObjects.LoginPage.login_page.LoginPage object at 0x0486BD30>, <PageObjects.index_page.index_page.IndexPage object at 0x0486BC30>)\n\n    @allure.story('用户名和密码异常-登录失败')\n    # @pytest.mark.flaky(reruns=2, reruns_delay=5)\n    @pytest.mark.parametrize('data', login_datas.error_passwordFormat_data)\n    def test_login02(self, data, login_driver):\n        \"\"\"\n        :param data:测试数据\n        :param login_driver:登录函数\n        :return: login_driver如果没有返回值，就不需要传参\n        步骤：\n        登录页面-获取错误提示信息-用户名和密码异常-登录失败\n        断言-登录界面-获取错误提示信息，获取提示语的text\n        \"\"\"\n        with allure.step('1.输入用户名：{}。 '\n                         '2.输入密码：{}。 '\n                         '3.点击登录'.format(data['membMobile'], data['membPassword'])):\n            try:\n                img_doc = data['dataName']\n                login_driver[0].login(data['membMobile'], data['membPassword'])\n                assert data['errorMsg'] == login_driver[0].get_err()\n            except Exception as e:\n                login_driver[0].save_screen_shoot(img_doc)\n>               raise e\n\nTestCases\\LoginCases\\test_login.py:54: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <test_login.TestLogin object at 0x0443E350>\ndata = {'dataName': '密码超过6位登录失败', 'errorMsg': '', 'membMobile': '15691750516', 'membPassword': '1234567890'}\nlogin_driver = (<PageObjects.LoginPage.login_page.LoginPage object at 0x0486BD30>, <PageObjects.index_page.index_page.IndexPage object at 0x0486BC30>)\n\n    @allure.story('用户名和密码异常-登录失败')\n    # @pytest.mark.flaky(reruns=2, reruns_delay=5)\n    @pytest.mark.parametrize('data', login_datas.error_passwordFormat_data)\n    def test_login02(self, data, login_driver):\n        \"\"\"\n        :param data:测试数据\n        :param login_driver:登录函数\n        :return: login_driver如果没有返回值，就不需要传参\n        步骤：\n        登录页面-获取错误提示信息-用户名和密码异常-登录失败\n        断言-登录界面-获取错误提示信息，获取提示语的text\n        \"\"\"\n        with allure.step('1.输入用户名：{}。 '\n                         '2.输入密码：{}。 '\n                         '3.点击登录'.format(data['membMobile'], data['membPassword'])):\n            try:\n                img_doc = data['dataName']\n                login_driver[0].login(data['membMobile'], data['membPassword'])\n>               assert data['errorMsg'] == login_driver[0].get_err()\nE               AssertionError: assert '' == '账号或密码错误!'\nE                 + 账号或密码错误!\n\nTestCases\\LoginCases\\test_login.py:51: AssertionError"}, "description": "\n        :param data:测试数据\n        :param login_driver:登录函数\n        :return: login_driver如果没有返回值，就不需要传参\n        步骤：\n        登录页面-获取错误提示信息-用户名和密码异常-登录失败\n        断言-登录界面-获取错误提示信息，获取提示语的text\n        ", "steps": [{"name": "1.输入用户名：15691750516。 2.输入密码：1234567890。 3.点击登录", "status": "failed", "statusDetails": {"message": "AssertionError: assert '' == '账号或密码错误!'\n  + 账号或密码错误!\n", "trace": "  File \"F:\\Automate_Test\\TestCases\\LoginCases\\test_login.py\", line 54, in test_login02\n    raise e\n  File \"F:\\Automate_Test\\TestCases\\LoginCases\\test_login.py\", line 51, in test_login02\n    assert data['errorMsg'] == login_driver[0].get_err()\n"}, "attachments": [{"name": "密码超过6位登录失败", "source": "875fe490-8f3c-4126-8f40-f89e1fb361c9-attachment.png", "type": "image/png"}], "start": 1597828533065, "stop": 1597828533880}], "attachments": [{"name": "log", "source": "c5cdaa5e-b9cb-4fbb-ace7-f01680573990-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'membMobile': '15691750516', 'membPassword': '1234567890', 'errorMsg': '', 'dataName': '密码超过6位登录失败'}"}], "start": 1597828533065, "stop": 1597828533880, "uuid": "e3f85a61-11c1-4bf3-b9b0-6470e2c69430", "historyId": "51f9ac2a6bb0def6965652fd1f8fb185", "testCaseId": "2ff383bdff515c30cf642e1f3e9ef869", "fullName": "TestCases.LoginCases.test_login.TestLogin#test_login02", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "用户名和密码异常-登录失败"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "TestCases.LoginCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "SC-201809291809"}, {"name": "thread", "value": "10812-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.LoginCases.test_login"}], "links": [{"type": "issue", "url": "https://oms.sdhwlw.com/", "name": "https://oms.sdhwlw.com/"}]}